SELECT AVG(TOTAL_AMOUNT) AS AVG_BOOKING_VALUE
FROM GOLD_BOOKING_CLEAN;

SELECT SUM(NUM_GUEST) AS TOTAL_GUESTS
FROM GOLD_BOOKING_CLEAN;

SELECT COUNT(*) AS TOTAL_BOOKINGS
FROM GOLD_BOOKING_CLEAN;

SELECT SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE
FROM GOLD_BOOKING_CLEAN;

SELECT DATE, TOTAL_REVENUE
FROM GOLD_AGG_DAILY_BOOKING
ORDER BY DATE;

SELECT DATE, TOTAL_BOOKING
FROM GOLD_AGG_DAILY_BOOKING
ORDER BY DATE;

SELECT HOTEL_CITY, TOTAL_REVENUE
FROM GOLD_AGG_HOTEL_CITY_SALES
WHERE TOTAL_REVENUE IS NOT NULL
ORDER BY TOTAL_REVENUE DESC
LIMIT 5;

SELECT BOOKING_STATUS, COUNT(*) AS TOTAL
FROM GOLD_BOOKING_CLEAN
GROUP BY BOOKING_STATUS;

SELECT ROOM_TYPE, COUNT(*) AS TOTAL_BOOKINGS
FROM GOLD_BOOKING_CLEAN
GROUP BY ROOM_TYPE
ORDER BY TOTAL_BOOKINGS DESC;
